### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by HasanKassem** [bartwell/ExFilePicker#15]
java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
at android.content.res.Resources.loadDrawable(Resources.java:3436)
at android.content.res.Resources.getDrawable(Resources.java:1909)
at android.widget.ImageView.resolveUri(ImageView.java:648)
at android.widget.ImageView.setImageResource(ImageView.java:377)
at ru.bartwell.exfilepicker.ExFilePickerActivity$FilesListAdapter$ThumbnailLoader.onPostExecute(ExFilePickerActivity.java:709)
at ru.bartwell.exfilepicker.ExFilePickerActivity$FilesListAdapter$ThumbnailLoader.onPostExecute(ExFilePickerActivity.java:650)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by M4RC1N** [comment]
I have the same issue.
java.lang.OutOfMemoryError
at ru.bartwell.exfilepicker.ExFilePickerActivity$FilesListAdapter$ThumbnailLoader.onPostExecute(Unknown Source)
	at ru.bartwell.exfilepicker.ExFilePickerActivity$FilesListAdapter$ThumbnailLoader.onPostExecute(Unknown Source)

**Comment by bartwell** [comment]
Fixed in version 2.1.
