### ISSUE TITLE
Missing com.bumptech.glide.Glide?

### ISSUE THREAD

**Issue by npes87184** [bartwell/ExFilePicker#26]
I use library-release.aar.
And when I enter some directory it will crash and the stack as follow:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.npes87184.s2tdroid, PID: 30809
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
                                                                            at ru.bartwell.exfilepicker.ui.adapter.holder.FileFilesListHolder.bind(FileFilesListHolder.java:44)
                                                                            at ru.bartwell.exfilepicker.ui.adapter.FilesListAdapter.onBindViewHolder(FilesListAdapter.java:87)
                                                                            at ru.bartwell.exfilepicker.ui.adapter.FilesListAdapter.onBindViewHolder(FilesListAdapter.java:29)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6310)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at com.android.internal.policy.DecorView.onLayout(DecorView.java:752)
                                                                            at android.view.View.layout(View.java:17747)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5596)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2477)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2178)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1328)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:890)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:692)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:876)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 09:21:19.795 30809-30809/com.npes87184.s2tdroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:173)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6519)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:849)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathList[[zip file "/data/app/com.npes87184.s2tdroid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.npes87184.s2tdroid-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            	... 59 more

**Comment by bartwell** [comment]
Hello! Are you using Proguard? You can setup as described here: http://bumptech.github.io/glide/doc/download-setup.html

**Comment by bartwell** [comment]
Please feel free to re-open this issue if you need.

**Comment by npes87184** [comment]
Ok, I will try and test when I have time. Sorry for the late reply.
